# htmltest configuration
# https://github.com/wjdp/htmltest

DirectoryPath: "public"

# Internal link checking (recommended)
CheckInternal: true

# External link checking (disabled for speed)
# Enable for thorough checks: CheckExternal: true
CheckExternal: false

# Skip mailto: and tel: links
CheckMailto: false
CheckTel: false

# Ignore these directories
IgnoreDirs:
  - "tags"
  - "categories"
  - "page"

# Ignore these URL patterns
IgnoreURLs:
  - "localhost"
  - "127.0.0.1"
  - "example.com"

# Ignore these alt text patterns
IgnoreAltMissing: false

# Output file (optional)
# OutputDir: ".htmltest"
# OutputFile: "report.json"

# Concurrency (adjust based on system)
# Concurrency: 4

# Timeout for external requests (seconds)
# ExternalTimeout: 10
